### ISSUE TITLE
Missing 'TabUtil' from the scripts directory

### ISSUE THREAD

**Issue by xAutomator** [orange451/RSGui#1]
Hello,

I really like the look of your project. I was trying to get it working but It appears to be missing the following import. Do you mind providing this source.

https://github.com/orange451/RSGui/blob/819993d871921f85b8c89cf8c0d3a1974818de4a/scripts/rsgui/RSGuiTab.java#L19

Thank you in advance!

**Comment by orange451** [comment]
Hey there! It should be in here:
https://github.com/orange451/RSUtil
