### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by ben-maher** [orange451/RSGui#2]
Hi there,
I was hoping to implement this UI and btw it looks really nice on the demo! 
I was attempting to implement it however, it looks like your sprite sheet and font files have been removed from the host you have in RSGuiRes.java

I found some similar font files online but for obvious reasons, could get the sprite sheet.
If you still have that it'd be great?

Thanks

**Comment by orange451** [comment]
Hey could you share the one you happened to find? I actually lost the original one, but could probably recreate it with a reference. I reset the virtual machine that hosted these files a few months ago, and forgot to take a backup.

[EDIT] Nevermind I misread your comment. I'll see what I can do about fully recreating the sprite sheet!

**Comment by ben-maher** [comment]
Thanks for the speedy reply!
I'm sorry to hear you lost it, that sucks so bad. I've searched around google and a few forums, I couldn't find it anywhere unfortunately. 

From the same file I mentioned before the fonts are also missing, I threw up some fonts I thought might be similar, [Here](https://github.com/benmaher95/Runescape-Fonts) hopefully they kinda match if you haven't got the fonts either.

Best of luck with the sprite sheet :)

**Comment by orange451** [comment]
I managed to set everything back up:
https://firstrecon.net/public/tribot/spritesheet.png

I think this should be functioning normally again!

**Comment by ben-maher** [comment]
Ah, you hero! 
I'll close this off now,
Thanks bud!
